server:
  port: 8082

directory:
  api:
    base-path: /api/experts

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/experts_db
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.integration.IntegrationAutoConfiguration
