server:
  port: ${SERVER_PORT:8083}

directory:
  api:
    base-path: /api/providers

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/providers_db
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.integration.IntegrationAutoConfiguration
